# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_2d_viewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Viewer2D(object):
    def setupUi(self, Viewer2D):
        Viewer2D.setObjectName("Viewer2D")
        Viewer2D.resize(400, 400)
        Viewer2D.setMinimumSize(QtCore.QSize(400, 400))
        self.verticalLayout = QtWidgets.QVBoxLayout(Viewer2D)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView2D = CustomGraphicsView(Viewer2D)
        self.graphicsView2D.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView2D.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView2D.setObjectName("graphicsView2D")
        self.verticalLayout.addWidget(self.graphicsView2D)

        self.retranslateUi(Viewer2D)
        QtCore.QMetaObject.connectSlotsByName(Viewer2D)

    def retranslateUi(self, Viewer2D):
        _translate = QtCore.QCoreApplication.translate
        Viewer2D.setWindowTitle(_translate("Viewer2D", "Form"))
from oat.views import CustomGraphicsView
