# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_add_collection_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddCollectionDialog(object):
    def setupUi(self, AddCollectionDialog):
        AddCollectionDialog.setObjectName("AddCollectionDialog")
        AddCollectionDialog.resize(321, 155)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddCollectionDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(AddCollectionDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.nameEdit = QtWidgets.QLineEdit(AddCollectionDialog)
        self.nameEdit.setObjectName("nameEdit")
        self.verticalLayout_3.addWidget(self.nameEdit)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(AddCollectionDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.od_button = QtWidgets.QRadioButton(AddCollectionDialog)
        self.od_button.setObjectName("od_button")
        self.horizontalLayout.addWidget(self.od_button)
        self.os_button = QtWidgets.QRadioButton(AddCollectionDialog)
        self.os_button.setObjectName("os_button")
        self.horizontalLayout.addWidget(self.os_button)
        self.na_button = QtWidgets.QRadioButton(AddCollectionDialog)
        self.na_button.setChecked(True)
        self.na_button.setObjectName("na_button")
        self.horizontalLayout.addWidget(self.na_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(AddCollectionDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(AddCollectionDialog)
        self.buttonBox.accepted.connect(AddCollectionDialog.accept)
        self.buttonBox.rejected.connect(AddCollectionDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AddCollectionDialog)

    def retranslateUi(self, AddCollectionDialog):
        _translate = QtCore.QCoreApplication.translate
        AddCollectionDialog.setWindowTitle(_translate("AddCollectionDialog", "Dialog"))
        self.label.setText(_translate("AddCollectionDialog", "Name"))
        self.label_2.setText(_translate("AddCollectionDialog", "Laterality"))
        self.od_button.setText(_translate("AddCollectionDialog", "OD"))
        self.os_button.setText(_translate("AddCollectionDialog", "OS"))
        self.na_button.setText(_translate("AddCollectionDialog", "NA"))
