# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_add_areaannotation_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AreaAnnotationDialog(object):
    def setupUi(self, AreaAnnotationDialog):
        AreaAnnotationDialog.setObjectName("AreaAnnotationDialog")
        AreaAnnotationDialog.resize(400, 159)
        self.verticalLayout = QtWidgets.QVBoxLayout(AreaAnnotationDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.typeLabel = QtWidgets.QLabel(AreaAnnotationDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.typeLabel.setFont(font)
        self.typeLabel.setObjectName("typeLabel")
        self.verticalLayout.addWidget(self.typeLabel)
        self.typeLayout = QtWidgets.QHBoxLayout()
        self.typeLayout.setObjectName("typeLayout")
        self.typeDropdown = QtWidgets.QComboBox(AreaAnnotationDialog)
        self.typeDropdown.setObjectName("typeDropdown")
        self.typeLayout.addWidget(self.typeDropdown)
        self.addTypeButton = QtWidgets.QToolButton(AreaAnnotationDialog)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/baseline-add_circle-24px.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addTypeButton.setIcon(icon)
        self.addTypeButton.setIconSize(QtCore.QSize(24, 24))
        self.addTypeButton.setObjectName("addTypeButton")
        self.typeLayout.addWidget(self.addTypeButton)
        self.verticalLayout.addLayout(self.typeLayout)
        self.label = QtWidgets.QLabel(AreaAnnotationDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox = QtWidgets.QCheckBox(AreaAnnotationDialog)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_2 = QtWidgets.QLabel(AreaAnnotationDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_3 = QtWidgets.QCheckBox(AreaAnnotationDialog)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_2.addWidget(self.checkBox_3)
        self.checkBox_2 = QtWidgets.QCheckBox(AreaAnnotationDialog)
        self.checkBox_2.setEnabled(False)
        self.checkBox_2.setCheckable(True)
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setTristate(False)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_2.addWidget(self.checkBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(AreaAnnotationDialog)
        self.buttonBox.setEnabled(True)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(AreaAnnotationDialog)
        self.buttonBox.accepted.connect(AreaAnnotationDialog.accept)
        self.buttonBox.rejected.connect(AreaAnnotationDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AreaAnnotationDialog)

    def retranslateUi(self, AreaAnnotationDialog):
        _translate = QtCore.QCoreApplication.translate
        AreaAnnotationDialog.setWindowTitle(_translate("AreaAnnotationDialog", "Dialog"))
        self.typeLabel.setText(_translate("AreaAnnotationDialog", "Areas:"))
        self.addTypeButton.setText(_translate("AreaAnnotationDialog", "+"))
        self.label.setText(_translate("AreaAnnotationDialog", "Layers:"))
        self.checkBox.setText(_translate("AreaAnnotationDialog", "CheckBox"))
        self.label_2.setText(_translate("AreaAnnotationDialog", "Settings:"))
        self.checkBox_3.setText(_translate("AreaAnnotationDialog", "Add to all B-Scans"))
        self.checkBox_2.setText(_translate("AreaAnnotationDialog", "Add to all modalities"))
from . import resources_rc
