# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_annotation_view.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AnnotationView(object):
    def setupUi(self, AnnotationView):
        AnnotationView.setObjectName("AnnotationView")
        AnnotationView.resize(856, 488)
        self.horizontalLayout = QtWidgets.QHBoxLayout(AnnotationView)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_5 = QtWidgets.QWidget(AnnotationView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(200)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.volumeWidget = VolumeLocalizerView(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.volumeWidget.sizePolicy().hasHeightForWidth())
        self.volumeWidget.setSizePolicy(sizePolicy)
        self.volumeWidget.setObjectName("volumeWidget")
        self.horizontalLayout_2.addWidget(self.volumeWidget)
        spacerItem1 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_5.addItem(spacerItem2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.graphicsViewEnface = EnfaceView(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.graphicsViewEnface.sizePolicy().hasHeightForWidth())
        self.graphicsViewEnface.setSizePolicy(sizePolicy)
        self.graphicsViewEnface.setMinimumSize(QtCore.QSize(200, 200))
        self.graphicsViewEnface.setObjectName("graphicsViewEnface")
        self.horizontalLayout_3.addWidget(self.graphicsViewEnface)
        spacerItem4 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addWidget(self.widget_5)
        self.widget = QtWidgets.QWidget(AnnotationView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.layerOverview = QtWidgets.QTabWidget(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layerOverview.sizePolicy().hasHeightForWidth())
        self.layerOverview.setSizePolicy(sizePolicy)
        self.layerOverview.setMinimumSize(QtCore.QSize(170, 250))
        self.layerOverview.setElideMode(QtCore.Qt.ElideNone)
        self.layerOverview.setObjectName("layerOverview")
        self.verticalLayout_2.addWidget(self.layerOverview)
        self.toolboxWidget = QtWidgets.QWidget(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolboxWidget.sizePolicy().hasHeightForWidth())
        self.toolboxWidget.setSizePolicy(sizePolicy)
        self.toolboxWidget.setObjectName("toolboxWidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.toolboxWidget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.toolsLabel = QtWidgets.QLabel(self.toolboxWidget)
        self.toolsLabel.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.toolsLabel.setFont(font)
        self.toolsLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.toolsLabel.setObjectName("toolsLabel")
        self.verticalLayout_7.addWidget(self.toolsLabel)
        self.toolsWidget = QtWidgets.QWidget(self.toolboxWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolsWidget.sizePolicy().hasHeightForWidth())
        self.toolsWidget.setSizePolicy(sizePolicy)
        self.toolsWidget.setObjectName("toolsWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.toolsWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_7.addWidget(self.toolsWidget)
        self.optionsLabel = QtWidgets.QLabel(self.toolboxWidget)
        self.optionsLabel.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.optionsLabel.setFont(font)
        self.optionsLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.optionsLabel.setObjectName("optionsLabel")
        self.verticalLayout_7.addWidget(self.optionsLabel)
        self.optionsWidget = QtWidgets.QWidget(self.toolboxWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.optionsWidget.sizePolicy().hasHeightForWidth())
        self.optionsWidget.setSizePolicy(sizePolicy)
        self.optionsWidget.setObjectName("optionsWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.optionsWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_7.addWidget(self.optionsWidget)
        self.verticalLayout_2.addWidget(self.toolboxWidget)
        self.verticalLayout_4.addWidget(self.widget_2)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(AnnotationView)
        self.layerOverview.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(AnnotationView)

    def retranslateUi(self, AnnotationView):
        _translate = QtCore.QCoreApplication.translate
        AnnotationView.setWindowTitle(_translate("AnnotationView", "Multimodal Annotation"))
        self.label_4.setText(_translate("AnnotationView", "Layers"))
        self.toolsLabel.setText(_translate("AnnotationView", "Tools"))
        self.optionsLabel.setText(_translate("AnnotationView", "Tool Options Test"))


from oat.modules.annotation.views.enface_view import EnfaceView
from oat.modules.annotation.views.volume_localizer_view import VolumeLocalizerView
from . import resources_rc
