# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_annotation_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AnnotationView(object):
    def setupUi(self, AnnotationView):
        AnnotationView.setObjectName("AnnotationView")
        AnnotationView.resize(856, 488)
        self.horizontalLayout = QtWidgets.QHBoxLayout(AnnotationView)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.data_widget = QtWidgets.QWidget(AnnotationView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(200)
        sizePolicy.setVerticalStretch(200)
        sizePolicy.setHeightForWidth(self.data_widget.sizePolicy().hasHeightForWidth())
        self.data_widget.setSizePolicy(sizePolicy)
        self.data_widget.setAutoFillBackground(False)
        self.data_widget.setStyleSheet("")
        self.data_widget.setObjectName("data_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.data_widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout.addWidget(self.data_widget)
        self.widget_2 = QtWidgets.QWidget(AnnotationView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.layerOverview = QtWidgets.QTabWidget(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layerOverview.sizePolicy().hasHeightForWidth())
        self.layerOverview.setSizePolicy(sizePolicy)
        self.layerOverview.setMinimumSize(QtCore.QSize(170, 250))
        self.layerOverview.setElideMode(QtCore.Qt.ElideNone)
        self.layerOverview.setObjectName("layerOverview")
        self.verticalLayout_2.addWidget(self.layerOverview)
        self.horizontalLayout.addWidget(self.widget_2)

        self.retranslateUi(AnnotationView)
        self.layerOverview.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(AnnotationView)

    def retranslateUi(self, AnnotationView):
        _translate = QtCore.QCoreApplication.translate
        AnnotationView.setWindowTitle(_translate("AnnotationView", "Multimodal Annotation"))
from . import resources_rc
