# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_data_overview.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OverviewView(object):
    def setupUi(self, OverviewView):
        OverviewView.setObjectName("OverviewView")
        OverviewView.resize(200, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(OverviewView.sizePolicy().hasHeightForWidth())
        OverviewView.setSizePolicy(sizePolicy)
        OverviewView.setMinimumSize(QtCore.QSize(200, 500))
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(OverviewView)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tableView = QtWidgets.QTableView(OverviewView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setObjectName("tableView")
        self.horizontalLayout_4.addWidget(self.tableView)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.registerButton = QtWidgets.QPushButton(OverviewView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.registerButton.sizePolicy().hasHeightForWidth())
        self.registerButton.setSizePolicy(sizePolicy)
        self.registerButton.setMinimumSize(QtCore.QSize(80, 0))
        self.registerButton.setBaseSize(QtCore.QSize(0, 0))
        self.registerButton.setIconSize(QtCore.QSize(16, 16))
        self.registerButton.setObjectName("registerButton")
        self.verticalLayout.addWidget(self.registerButton)
        self.annotateButton = QtWidgets.QPushButton(OverviewView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.annotateButton.sizePolicy().hasHeightForWidth())
        self.annotateButton.setSizePolicy(sizePolicy)
        self.annotateButton.setMinimumSize(QtCore.QSize(80, 0))
        self.annotateButton.setObjectName("annotateButton")
        self.verticalLayout.addWidget(self.annotateButton)
        spacerItem = QtWidgets.QSpacerItem(80, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_4.addLayout(self.verticalLayout)

        self.retranslateUi(OverviewView)
        QtCore.QMetaObject.connectSlotsByName(OverviewView)

    def retranslateUi(self, OverviewView):
        _translate = QtCore.QCoreApplication.translate
        OverviewView.setWindowTitle(_translate("OverviewView", "Data Collections"))
        self.registerButton.setText(_translate("OverviewView", "Register"))
        self.annotateButton.setText(_translate("OverviewView", "Annotate"))
from . import resources_rc
