# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_data_navigation_dock.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dataNavigationDock(object):
    def setupUi(self, dataNavigationDock):
        dataNavigationDock.setObjectName("dataNavigationDock")
        dataNavigationDock.resize(350, 432)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dataNavigationDock.sizePolicy().hasHeightForWidth())
        dataNavigationDock.setSizePolicy(sizePolicy)
        dataNavigationDock.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        dataNavigationDock.setWindowTitle("")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setMinimumSize(QtCore.QSize(350, 200))
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.datasetComboBox = QtWidgets.QComboBox(self.dockWidgetContents)
        self.datasetComboBox.setObjectName("datasetComboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.datasetComboBox)
        self.horizontalLayout.addLayout(self.formLayout)
        self.toolButton = QtWidgets.QToolButton(self.dockWidgetContents)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/baseline-add_circle-24px.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setIconSize(QtCore.QSize(24, 24))
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout.addWidget(self.toolButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableView = QtWidgets.QTableView(self.dockWidgetContents)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_3.addWidget(self.tableView)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.addButton = QtWidgets.QToolButton(self.dockWidgetContents)
        self.addButton.setIcon(icon)
        self.addButton.setIconSize(QtCore.QSize(24, 24))
        self.addButton.setObjectName("addButton")
        self.horizontalLayout_3.addWidget(self.addButton)
        self.deleteButton = QtWidgets.QToolButton(self.dockWidgetContents)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/baseline-delete-24px.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteButton.setIcon(icon1)
        self.deleteButton.setIconSize(QtCore.QSize(24, 24))
        self.deleteButton.setObjectName("deleteButton")
        self.horizontalLayout_3.addWidget(self.deleteButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.registerButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.registerButton.setObjectName("registerButton")
        self.verticalLayout.addWidget(self.registerButton)
        self.annotateButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.annotateButton.setObjectName("annotateButton")
        self.verticalLayout.addWidget(self.annotateButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        dataNavigationDock.setWidget(self.dockWidgetContents)

        self.retranslateUi(dataNavigationDock)
        QtCore.QMetaObject.connectSlotsByName(dataNavigationDock)

    def retranslateUi(self, dataNavigationDock):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("dataNavigationDock", "Dataset:"))
        self.toolButton.setText(_translate("dataNavigationDock", "..."))
        self.addButton.setText(_translate("dataNavigationDock", "..."))
        self.deleteButton.setText(_translate("dataNavigationDock", "..."))
        self.registerButton.setText(_translate("dataNavigationDock", "Register"))
        self.annotateButton.setText(_translate("dataNavigationDock", "Annotate"))
from . import resources_rc
