# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_layer_entry.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LayerEntry(object):
    def setupUi(self, LayerEntry):
        LayerEntry.setObjectName("LayerEntry")
        LayerEntry.resize(150, 30)
        LayerEntry.setMinimumSize(QtCore.QSize(150, 30))
        LayerEntry.setMaximumSize(QtCore.QSize(300, 30))
        LayerEntry.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        LayerEntry.setAutoFillBackground(False)
        LayerEntry.setStyleSheet("background-color: white")
        self.horizontalLayout = QtWidgets.QHBoxLayout(LayerEntry)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.hideButton = QtWidgets.QToolButton(LayerEntry)
        self.hideButton.setMinimumSize(QtCore.QSize(26, 26))
        self.hideButton.setMaximumSize(QtCore.QSize(26, 26))
        self.hideButton.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.hideButton.setStyleSheet("background-color: white")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/baseline-visibility-24px.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.hideButton.setIcon(icon)
        self.hideButton.setIconSize(QtCore.QSize(24, 24))
        self.hideButton.setObjectName("hideButton")
        self.horizontalLayout.addWidget(self.hideButton)
        self.colorButton = QtWidgets.QToolButton(LayerEntry)
        self.colorButton.setMinimumSize(QtCore.QSize(26, 26))
        self.colorButton.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.colorButton.setAutoFillBackground(False)
        self.colorButton.setStyleSheet("background-color: white")
        self.colorButton.setText("")
        self.colorButton.setObjectName("colorButton")
        self.horizontalLayout.addWidget(self.colorButton)
        self.label = QtWidgets.QLabel(LayerEntry)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("")
        self.label.setScaledContents(False)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)

        self.retranslateUi(LayerEntry)
        QtCore.QMetaObject.connectSlotsByName(LayerEntry)

    def retranslateUi(self, LayerEntry):
        _translate = QtCore.QCoreApplication.translate
        LayerEntry.setWindowTitle(_translate("LayerEntry", "Form"))
        self.hideButton.setText(_translate("LayerEntry", "..."))
        self.label.setText(_translate("LayerEntry", "Layer Name"))
from . import resources_rc
