# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(836, 637)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setViewMode(QtWidgets.QMdiArea.SubWindowView)
        self.mdiArea.setObjectName("mdiArea")
        self.verticalLayout.addWidget(self.mdiArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 836, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuUpload = QtWidgets.QMenu(self.menuFile)
        self.menuUpload.setObjectName("menuUpload")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionOpen_Project = QtWidgets.QAction(MainWindow)
        self.actionOpen_Project.setObjectName("actionOpen_Project")
        self.action_vol = QtWidgets.QAction(MainWindow)
        self.action_vol.setEnabled(True)
        self.action_vol.setObjectName("action_vol")
        self.actionToggle2D = QtWidgets.QAction(MainWindow)
        self.actionToggle2D.setCheckable(True)
        self.actionToggle2D.setChecked(True)
        self.actionToggle2D.setEnabled(True)
        self.actionToggle2D.setObjectName("actionToggle2D")
        self.actionToggle3D = QtWidgets.QAction(MainWindow)
        self.actionToggle3D.setCheckable(True)
        self.actionToggle3D.setChecked(True)
        self.actionToggle3D.setObjectName("actionToggle3D")
        self.actionToogleToolbox = QtWidgets.QAction(MainWindow)
        self.actionToogleToolbox.setCheckable(True)
        self.actionToogleToolbox.setChecked(True)
        self.actionToogleToolbox.setObjectName("actionToogleToolbox")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/baseline-undo-24px.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUndo.setIcon(icon)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/baseline-redo-24px.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRedo.setIcon(icon1)
        self.actionRedo.setObjectName("actionRedo")
        self.action_cfp = QtWidgets.QAction(MainWindow)
        self.action_cfp.setObjectName("action_cfp")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionUploadVol = QtWidgets.QAction(MainWindow)
        self.actionUploadVol.setObjectName("actionUploadVol")
        self.actionUploadCfp = QtWidgets.QAction(MainWindow)
        self.actionUploadCfp.setObjectName("actionUploadCfp")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.menuUpload.addAction(self.actionUploadVol)
        self.menuUpload.addAction(self.actionUploadCfp)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuUpload.menuAction())
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExport)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EyeLab"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuUpload.setTitle(_translate("MainWindow", "Upload"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as"))
        self.actionOpen_Project.setText(_translate("MainWindow", "Open Project"))
        self.action_vol.setText(_translate("MainWindow", "HE raw Export (.vol )"))
        self.actionToggle2D.setText(_translate("MainWindow", "2D Viewer"))
        self.actionToggle3D.setText(_translate("MainWindow", "3D Viewer"))
        self.actionToogleToolbox.setText(_translate("MainWindow", "Toolbox"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionUndo.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionRedo.setShortcut(_translate("MainWindow", "Ctrl+Y"))
        self.action_cfp.setText(_translate("MainWindow", "CFP (.bmp/.tif/.jpg)"))
        self.actionExport.setText(_translate("MainWindow", "Export"))
        self.actionUploadVol.setText(_translate("MainWindow", "Heyex Raw (.vol)"))
        self.actionUploadCfp.setText(_translate("MainWindow", "CFP (.tiff/.bmp)"))
        self.actionSave.setText(_translate("MainWindow", "Save"))


from . import resources_rc
