# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_pen_options.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_penOptions(object):
    def setupUi(self, penOptions):
        penOptions.setObjectName("penOptions")
        penOptions.resize(126, 56)
        penOptions.setWindowTitle("")
        self.verticalLayout = QtWidgets.QVBoxLayout(penOptions)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(penOptions)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(5, -1, -1, -1)
        self.formLayout.setSpacing(2)
        self.formLayout.setObjectName("formLayout")
        self.sizeLabel = QtWidgets.QLabel(penOptions)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.sizeLabel.setFont(font)
        self.sizeLabel.setObjectName("sizeLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.sizeLabel)
        self.sizeSlider = QtWidgets.QSlider(penOptions)
        self.sizeSlider.setMinimum(1)
        self.sizeSlider.setMaximum(100)
        self.sizeSlider.setProperty("value", 5)
        self.sizeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.sizeSlider.setObjectName("sizeSlider")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sizeSlider)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(penOptions)
        QtCore.QMetaObject.connectSlotsByName(penOptions)

    def retranslateUi(self, penOptions):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("penOptions", "Pen:"))
        self.sizeLabel.setText(_translate("penOptions", "Size:"))
