# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_registration_manual.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegistrationManual(object):
    def setupUi(self, RegistrationManual):
        RegistrationManual.setObjectName("RegistrationManual")
        RegistrationManual.resize(820, 490)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(RegistrationManual.sizePolicy().hasHeightForWidth())
        RegistrationManual.setSizePolicy(sizePolicy)
        RegistrationManual.setMinimumSize(QtCore.QSize(820, 490))
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(RegistrationManual)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.graphicsViewPointSelection = FeatureSelectionView(RegistrationManual)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsViewPointSelection.sizePolicy().hasHeightForWidth())
        self.graphicsViewPointSelection.setSizePolicy(sizePolicy)
        self.graphicsViewPointSelection.setMinimumSize(QtCore.QSize(300, 300))
        self.graphicsViewPointSelection.setBaseSize(QtCore.QSize(200, 200))
        self.graphicsViewPointSelection.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsViewPointSelection.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsViewPointSelection.setObjectName("graphicsViewPointSelection")
        self.horizontalLayout.addWidget(self.graphicsViewPointSelection)
        spacerItem = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.graphicsViewCheckerboard = CustomGraphicsView(RegistrationManual)
        self.graphicsViewCheckerboard.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsViewCheckerboard.sizePolicy().hasHeightForWidth())
        self.graphicsViewCheckerboard.setSizePolicy(sizePolicy)
        self.graphicsViewCheckerboard.setMinimumSize(QtCore.QSize(300, 300))
        self.graphicsViewCheckerboard.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.graphicsViewCheckerboard.setSizeIncrement(QtCore.QSize(0, 0))
        self.graphicsViewCheckerboard.setBaseSize(QtCore.QSize(200, 200))
        self.graphicsViewCheckerboard.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsViewCheckerboard.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsViewCheckerboard.setObjectName("graphicsViewCheckerboard")
        self.horizontalLayout.addWidget(self.graphicsViewCheckerboard)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(2, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.graphicsViewPatch = CustomGraphicsView(RegistrationManual)
        self.graphicsViewPatch.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsViewPatch.sizePolicy().hasHeightForWidth())
        self.graphicsViewPatch.setSizePolicy(sizePolicy)
        self.graphicsViewPatch.setMinimumSize(QtCore.QSize(150, 150))
        self.graphicsViewPatch.setMaximumSize(QtCore.QSize(150, 150))
        self.graphicsViewPatch.setSizeIncrement(QtCore.QSize(0, 0))
        self.graphicsViewPatch.setBaseSize(QtCore.QSize(100, 100))
        self.graphicsViewPatch.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsViewPatch.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsViewPatch.setObjectName("graphicsViewPatch")
        self.horizontalLayout_5.addWidget(self.graphicsViewPatch)
        spacerItem2 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.tableViewPoints = FeatureTableView(RegistrationManual)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableViewPoints.sizePolicy().hasHeightForWidth())
        self.tableViewPoints.setSizePolicy(sizePolicy)
        self.tableViewPoints.setMinimumSize(QtCore.QSize(300, 100))
        self.tableViewPoints.setMaximumSize(QtCore.QSize(16777215, 150))
        self.tableViewPoints.setBaseSize(QtCore.QSize(0, 0))
