# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_spline_options.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_splineOptions(object):
    def setupUi(self, splineOptions):
        splineOptions.setObjectName("splineOptions")
        splineOptions.resize(139, 109)
        splineOptions.setWindowTitle("")
        self.verticalLayout = QtWidgets.QVBoxLayout(splineOptions)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(splineOptions)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(5, -1, -1, -1)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.showCheckBox = QtWidgets.QCheckBox(splineOptions)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.showCheckBox.setFont(font)
        self.showCheckBox.setChecked(True)
        self.showCheckBox.setObjectName("showCheckBox")
        self.verticalLayout_2.addWidget(self.showCheckBox)
        self.strengthCheckBox = QtWidgets.QCheckBox(splineOptions)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.strengthCheckBox.setFont(font)
        self.strengthCheckBox.setChecked(True)
        self.strengthCheckBox.setObjectName("strengthCheckBox")
        self.verticalLayout_2.addWidget(self.strengthCheckBox)
        self.slopeCheckBox = QtWidgets.QCheckBox(splineOptions)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.slopeCheckBox.setFont(font)
        self.slopeCheckBox.setChecked(True)
        self.slopeCheckBox.setObjectName("slopeCheckBox")
        self.verticalLayout_2.addWidget(self.slopeCheckBox)
        self.neighbourCheckBox = QtWidgets.QCheckBox(splineOptions)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.neighbourCheckBox.setFont(font)
        self.neighbourCheckBox.setChecked(True)
        self.neighbourCheckBox.setObjectName("neighbourCheckBox")
        self.verticalLayout_2.addWidget(self.neighbourCheckBox)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(splineOptions)
        QtCore.QMetaObject.connectSlotsByName(splineOptions)

    def retranslateUi(self, splineOptions):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("splineOptions", "Control points:"))
        self.showCheckBox.setToolTip(_translate("splineOptions", "Hide the blue control points"))
        self.showCheckBox.setText(_translate("splineOptions", "Show"))
        self.strengthCheckBox.setToolTip(_translate("splineOptions", "Optimize control point position when moving a knot"))
        self.strengthCheckBox.setText(_translate("splineOptions", "Optimize strength"))
        self.slopeCheckBox.setText(_translate("splineOptions", "Optimize slope"))
        self.neighbourCheckBox.setText(_translate("splineOptions", "Optimize neighbours"))
