# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_text_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TextWindow(object):
    def setupUi(self, TextWindow):
        TextWindow.setObjectName("TextWindow")
        TextWindow.resize(400, 300)
        self.horizontalLayout = QtWidgets.QHBoxLayout(TextWindow)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textEdit = QtWidgets.QTextEdit(TextWindow)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout.addWidget(self.textEdit)

        self.retranslateUi(TextWindow)
        QtCore.QMetaObject.connectSlotsByName(TextWindow)

    def retranslateUi(self, TextWindow):
        _translate = QtCore.QCoreApplication.translate
        TextWindow.setWindowTitle(_translate("TextWindow", "Help"))
        self.textEdit.setHtml(_translate("TextWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
