# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_volumelocalizer_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VolumeLocalizerView(object):
    def setupUi(self, VolumeLocalizerView):
        VolumeLocalizerView.setObjectName("VolumeLocalizerView")
        VolumeLocalizerView.resize(734, 238)
        self.horizontalLayout = QtWidgets.QHBoxLayout(VolumeLocalizerView)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.graphicsViewLocalizer = EnfaceView(VolumeLocalizerView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.graphicsViewLocalizer.sizePolicy().hasHeightForWidth())
        self.graphicsViewLocalizer.setSizePolicy(sizePolicy)
        self.graphicsViewLocalizer.setMinimumSize(QtCore.QSize(200, 200))
        self.graphicsViewLocalizer.setObjectName("graphicsViewLocalizer")
        self.horizontalLayout.addWidget(self.graphicsViewLocalizer)
        spacerItem = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.graphicsViewVolume = VolumeView(VolumeLocalizerView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.graphicsViewVolume.sizePolicy().hasHeightForWidth())
        self.graphicsViewVolume.setSizePolicy(sizePolicy)
        self.graphicsViewVolume.setMinimumSize(QtCore.QSize(300, 200))
        self.graphicsViewVolume.setObjectName("graphicsViewVolume")
        self.horizontalLayout.addWidget(self.graphicsViewVolume)

        self.retranslateUi(VolumeLocalizerView)
        QtCore.QMetaObject.connectSlotsByName(VolumeLocalizerView)

    def retranslateUi(self, VolumeLocalizerView):
        _translate = QtCore.QCoreApplication.translate
        VolumeLocalizerView.setWindowTitle(_translate("VolumeLocalizerView", "Form"))
from oat.views.graphics import EnfaceView, VolumeView
from . import resources_rc
