# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_registration_manual.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegistrationManualView(object):
    def setupUi(self, RegistrationManualView):
        RegistrationManualView.setObjectName("RegistrationManualView")
        RegistrationManualView.resize(1381, 421)
        self.horizontalLayoutWidget = QtWidgets.QWidget(RegistrationManualView)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1381, 421))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableViewPoints = QtWidgets.QTableView(self.horizontalLayoutWidget)
        self.tableViewPoints.setObjectName("tableViewPoints")
        self.horizontalLayout_2.addWidget(self.tableViewPoints)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.graphicsViewFixedPatch = QtWidgets.QGraphicsView(self.horizontalLayoutWidget)
        self.graphicsViewFixedPatch.setObjectName("graphicsViewFixedPatch")
        self.horizontalLayout_2.addWidget(self.graphicsViewFixedPatch)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.graphicsViewPointsOverview = QtWidgets.QGraphicsView(self.horizontalLayoutWidget)
        self.graphicsViewPointsOverview.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsViewPointsOverview.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.graphicsViewPointsOverview.setObjectName("graphicsViewPointsOverview")
        self.verticalLayout.addWidget(self.graphicsViewPointsOverview)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.graphicsViewPointSelection = QtWidgets.QGraphicsView(self.horizontalLayoutWidget)
        self.graphicsViewPointSelection.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsViewPointSelection.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsViewPointSelection.setObjectName("graphicsViewPointSelection")
        self.verticalLayout_3.addWidget(self.graphicsViewPointSelection)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.backButton = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/baseline-navigate-before-24px.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.backButton.setIcon(icon)
        self.backButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.backButton.setObjectName("backButton")
        self.horizontalLayout_3.addWidget(self.backButton)
        self.saveButton = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/baseline-save-24px.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveButton.setIcon(icon1)
        self.saveButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout_3.addWidget(self.saveButton)
        self.nextButton = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/baseline-navigate-next-24px.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextButton.setIcon(icon2)
        self.nextButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout_3.addWidget(self.nextButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.graphicsViewCheckerboard = QtWidgets.QGraphicsView(self.horizontalLayoutWidget)
        self.graphicsViewCheckerboard.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsViewCheckerboard.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsViewCheckerboard.setObjectName("graphicsViewCheckerboard")
        self.verticalLayout_2.addWidget(self.graphicsViewCheckerboard)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.transformationDropdown = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.transformationDropdown.setObjectName("transformationDropdown")
        self.transformationDropdown.addItem("")
        self.transformationDropdown.addItem("")
        self.transformationDropdown.addItem("")
        self.transformationDropdown.addItem("")
        self.transformationDropdown.addItem("")
        self.verticalLayout_2.addWidget(self.transformationDropdown)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.gridSizeSlider = QtWidgets.QSlider(self.horizontalLayoutWidget)
        self.gridSizeSlider.setMinimum(10)
        self.gridSizeSlider.setMaximum(200)
        self.gridSizeSlider.setProperty("value", 50)
        self.gridSizeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.gridSizeSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.gridSizeSlider.setTickInterval(10)
        self.gridSizeSlider.setObjectName("gridSizeSlider")
        self.verticalLayout_2.addWidget(self.gridSizeSlider)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(RegistrationManualView)
        QtCore.QMetaObject.connectSlotsByName(RegistrationManualView)

    def retranslateUi(self, RegistrationManualView):
        _translate = QtCore.QCoreApplication.translate
        RegistrationManualView.setWindowTitle(_translate("RegistrationManualView", "Form"))
        self.backButton.setText(_translate("RegistrationManualView", "Back"))
        self.backButton.setShortcut(_translate("RegistrationManualView", "Backspace"))
        self.saveButton.setText(_translate("RegistrationManualView", "Save"))
        self.saveButton.setShortcut(_translate("RegistrationManualView", "Ctrl+S"))
        self.nextButton.setText(_translate("RegistrationManualView", "Next"))
        self.nextButton.setShortcut(_translate("RegistrationManualView", "Return"))
        self.label_2.setText(_translate("RegistrationManualView", "Transformation Model"))
        self.transformationDropdown.setItemText(0, _translate("RegistrationManualView", "Affine"))
        self.transformationDropdown.setItemText(1, _translate("RegistrationManualView", "Similarity"))
        self.transformationDropdown.setItemText(2, _translate("RegistrationManualView", "Quadratic"))
        self.transformationDropdown.setItemText(3, _translate("RegistrationManualView", "Moving Least Squares"))
        self.transformationDropdown.setItemText(4, _translate("RegistrationManualView", "Deformable"))
        self.label.setText(_translate("RegistrationManualView", "Gridsize"))


from . import resources_rc
