# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_toolbox.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Toolbox(object):
    def setupUi(self, Toolbox):
        Toolbox.setObjectName("Toolbox")
        Toolbox.resize(296, 505)
        Toolbox.setMinimumSize(QtCore.QSize(250, 470))
        Toolbox.setAccessibleName("")
        self.verticalLayout = QtWidgets.QVBoxLayout(Toolbox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Toolbox)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.tabWidget = QtWidgets.QTabWidget(self.widget)
        self.tabWidget.setObjectName("tabWidget")
        self.layers2d = QtWidgets.QWidget()
        self.layers2d.setObjectName("layers2d")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layers2d)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.opacitySliderLabel_2d = QtWidgets.QLabel(self.layers2d)
        self.opacitySliderLabel_2d.setObjectName("opacitySliderLabel_2d")
        self.verticalLayout_3.addWidget(self.opacitySliderLabel_2d)
        self.opacitySlider_2d = QtWidgets.QSlider(self.layers2d)
        self.opacitySlider_2d.setOrientation(QtCore.Qt.Horizontal)
        self.opacitySlider_2d.setObjectName("opacitySlider_2d")
        self.verticalLayout_3.addWidget(self.opacitySlider_2d)
        self.ModalityTreeView_2d = QtWidgets.QTreeView(self.layers2d)
        self.ModalityTreeView_2d.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.ModalityTreeView_2d.setObjectName("ModalityTreeView_2d")
        self.verticalLayout_3.addWidget(self.ModalityTreeView_2d)
        self.horizontalLayout_2d = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2d.setObjectName("horizontalLayout_2d")
        self.addButton_2d = QtWidgets.QToolButton(self.layers2d)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/baseline-add_circle-24px.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addButton_2d.setIcon(icon)
        self.addButton_2d.setIconSize(QtCore.QSize(24, 24))
        self.addButton_2d.setObjectName("addButton_2d")
        self.horizontalLayout_2d.addWidget(self.addButton_2d)
        self.upButton_2d = QtWidgets.QToolButton(self.layers2d)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/baseline-arrow_upward-24px.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.upButton_2d.setIcon(icon1)
        self.upButton_2d.setIconSize(QtCore.QSize(24, 24))
        self.upButton_2d.setObjectName("upButton_2d")
        self.horizontalLayout_2d.addWidget(self.upButton_2d)
        self.downButton_2d = QtWidgets.QToolButton(self.layers2d)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/baseline-arrow_downward-24px.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.downButton_2d.setIcon(icon2)
        self.downButton_2d.setIconSize(QtCore.QSize(24, 24))
        self.downButton_2d.setObjectName("downButton_2d")
        self.horizontalLayout_2d.addWidget(self.downButton_2d)
        self.deleteButton_2d = QtWidgets.QToolButton(self.layers2d)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/baseline-delete-24px.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteButton_2d.setIcon(icon3)
        self.deleteButton_2d.setIconSize(QtCore.QSize(24, 24))
        self.deleteButton_2d.setObjectName("deleteButton_2d")
        self.horizontalLayout_2d.addWidget(self.deleteButton_2d)
        self.registerButton_2d = QtWidgets.QToolButton(self.layers2d)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/baseline-filter-none-24px.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.registerButton_2d.setIcon(icon4)
        self.registerButton_2d.setIconSize(QtCore.QSize(24, 24))
        self.registerButton_2d.setObjectName("registerButton_2d")
        self.horizontalLayout_2d.addWidget(self.registerButton_2d)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2d)
        self.tabWidget.addTab(self.layers2d, "")
        self.layers3d = QtWidgets.QWidget()
        self.layers3d.setObjectName("layers3d")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layers3d)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.opacitySliderLabel_3d = QtWidgets.QLabel(self.layers3d)
        self.opacitySliderLabel_3d.setObjectName("opacitySliderLabel_3d")
        self.verticalLayout_6.addWidget(self.opacitySliderLabel_3d)
        self.opacitySlider_3d = QtWidgets.QSlider(self.layers3d)
        self.opacitySlider_3d.setOrientation(QtCore.Qt.Horizontal)
        self.opacitySlider_3d.setObjectName("opacitySlider_3d")
        self.verticalLayout_6.addWidget(self.opacitySlider_3d)
        self.ModalityTreeView_3d = QtWidgets.QTreeView(self.layers3d)
        self.ModalityTreeView_3d.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.ModalityTreeView_3d.setObjectName("ModalityTreeView_3d")
        self.verticalLayout_6.addWidget(self.ModalityTreeView_3d)
        self.horizontalLayout_3d = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3d.setObjectName("horizontalLayout_3d")
        self.addButton_3d = QtWidgets.QToolButton(self.layers3d)
        self.addButton_3d.setIcon(icon)
        self.addButton_3d.setIconSize(QtCore.QSize(24, 24))
        self.addButton_3d.setArrowType(QtCore.Qt.NoArrow)
        self.addButton_3d.setObjectName("addButton_3d")
        self.horizontalLayout_3d.addWidget(self.addButton_3d)
        self.upButton_3d = QtWidgets.QToolButton(self.layers3d)
        self.upButton_3d.setIcon(icon1)
        self.upButton_3d.setIconSize(QtCore.QSize(24, 24))
        self.upButton_3d.setObjectName("upButton_3d")
        self.horizontalLayout_3d.addWidget(self.upButton_3d)
        self.downButton_3d = QtWidgets.QToolButton(self.layers3d)
        self.downButton_3d.setIcon(icon2)
        self.downButton_3d.setIconSize(QtCore.QSize(24, 24))
        self.downButton_3d.setObjectName("downButton_3d")
        self.horizontalLayout_3d.addWidget(self.downButton_3d)
        self.deleteButton_3d = QtWidgets.QToolButton(self.layers3d)
        self.deleteButton_3d.setIcon(icon3)
        self.deleteButton_3d.setIconSize(QtCore.QSize(24, 24))
        self.deleteButton_3d.setObjectName("deleteButton_3d")
        self.horizontalLayout_3d.addWidget(self.deleteButton_3d)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3d)
        self.tabWidget.addTab(self.layers3d, "")
        self.verticalLayout_2.addWidget(self.tabWidget, 0, QtCore.Qt.AlignTop)
        self.verticalLayout.addWidget(self.widget)
        self.line = QtWidgets.QFrame(Toolbox)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.widget_3 = QtWidgets.QWidget(Toolbox)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_7.addWidget(self.label_2)
        self.widget_2 = QtWidgets.QWidget(self.widget_3)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout.setObjectName("gridLayout")
        self.toolButton_8 = QtWidgets.QToolButton(self.widget_2)
        self.toolButton_8.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_8.setObjectName("toolButton_8")
        self.gridLayout.addWidget(self.toolButton_8, 1, 3, 1, 1)
        self.toolButton_11 = QtWidgets.QToolButton(self.widget_2)
        self.toolButton_11.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_11.setObjectName("toolButton_11")
        self.gridLayout.addWidget(self.toolButton_11, 2, 2, 1, 1)
        self.penButton = QtWidgets.QToolButton(self.widget_2)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/baseline-edit-24px.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.penButton.setIcon(icon5)
        self.penButton.setIconSize(QtCore.QSize(24, 24))
        self.penButton.setObjectName("penButton")
        self.gridLayout.addWidget(self.penButton, 1, 0, 1, 1)
        self.toolButton_10 = QtWidgets.QToolButton(self.widget_2)
        self.toolButton_10.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_10.setObjectName("toolButton_10")
        self.gridLayout.addWidget(self.toolButton_10, 2, 1, 1, 1)
        self.toolButton_9 = QtWidgets.QToolButton(self.widget_2)
        self.toolButton_9.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_9.setObjectName("toolButton_9")
        self.gridLayout.addWidget(self.toolButton_9, 2, 0, 1, 1)
        self.toolButton_7 = QtWidgets.QToolButton(self.widget_2)
        self.toolButton_7.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_7.setObjectName("toolButton_7")
        self.gridLayout.addWidget(self.toolButton_7, 1, 1, 1, 1)
        self.toolButton_6 = QtWidgets.QToolButton(self.widget_2)
        self.toolButton_6.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_6.setObjectName("toolButton_6")
        self.gridLayout.addWidget(self.toolButton_6, 1, 2, 1, 1)
        self.toolButton_12 = QtWidgets.QToolButton(self.widget_2)
        self.toolButton_12.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_12.setObjectName("toolButton_12")
        self.gridLayout.addWidget(self.toolButton_12, 2, 3, 1, 1)
        self.verticalLayout_7.addWidget(self.widget_2)
        self.verticalLayout.addWidget(self.widget_3, 0, QtCore.Qt.AlignTop)

        self.retranslateUi(Toolbox)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Toolbox)

    def retranslateUi(self, Toolbox):
        _translate = QtCore.QCoreApplication.translate
        Toolbox.setWindowTitle(_translate("Toolbox", "Form"))
        self.label_3.setText(_translate("Toolbox", "Layers"))
        self.opacitySliderLabel_2d.setText(_translate("Toolbox", "Opacity"))
        self.addButton_2d.setText(_translate("Toolbox", "..."))
        self.upButton_2d.setText(_translate("Toolbox", "..."))
        self.downButton_2d.setText(_translate("Toolbox", "..."))
        self.deleteButton_2d.setText(_translate("Toolbox", "..."))
        self.registerButton_2d.setToolTip(_translate("Toolbox", "Register selected images"))
        self.registerButton_2d.setText(_translate("Toolbox", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.layers2d), _translate("Toolbox", "2D"))
        self.opacitySliderLabel_3d.setText(_translate("Toolbox", "Opacity"))
        self.addButton_3d.setText(_translate("Toolbox", "..."))
        self.upButton_3d.setText(_translate("Toolbox", "..."))
        self.downButton_3d.setText(_translate("Toolbox", "..."))
        self.deleteButton_3d.setText(_translate("Toolbox", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.layers3d), _translate("Toolbox", "3D"))
        self.label_2.setText(_translate("Toolbox", "Tools"))
        self.toolButton_8.setText(_translate("Toolbox", "..."))
        self.toolButton_11.setText(_translate("Toolbox", "..."))
        self.penButton.setText(_translate("Toolbox", "..."))
        self.toolButton_10.setText(_translate("Toolbox", "..."))
        self.toolButton_9.setText(_translate("Toolbox", "..."))
        self.toolButton_7.setText(_translate("Toolbox", "..."))
        self.toolButton_6.setText(_translate("Toolbox", "..."))
        self.toolButton_12.setText(_translate("Toolbox", "..."))
from . import resources_rc
