# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_toolbox.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Toolbox(object):
    def setupUi(self, Toolbox):
        Toolbox.setObjectName("Toolbox")
        Toolbox.resize(218, 441)
        Toolbox.setAccessibleName("")
        self.verticalLayout = QtWidgets.QVBoxLayout(Toolbox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Toolbox)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.opacitySlider = QtWidgets.QSlider(self.widget)
        self.opacitySlider.setOrientation(QtCore.Qt.Horizontal)
        self.opacitySlider.setObjectName("opacitySlider")
        self.verticalLayout_2.addWidget(self.opacitySlider)
        self.scrollArea = QtWidgets.QScrollArea(self.widget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 180, 169))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addButton = QtWidgets.QToolButton(self.widget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/baseline-add_circle-24px.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addButton.setIcon(icon)
        self.addButton.setIconSize(QtCore.QSize(24, 24))
        self.addButton.setObjectName("addButton")
        self.horizontalLayout.addWidget(self.addButton)
        self.upButton = QtWidgets.QToolButton(self.widget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../images/baseline-arrow_upward-24px.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.upButton.setIcon(icon1)
        self.upButton.setIconSize(QtCore.QSize(24, 24))
        self.upButton.setObjectName("upButton")
        self.horizontalLayout.addWidget(self.upButton)
        self.downButton = QtWidgets.QToolButton(self.widget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../images/baseline-arrow_downward-24px.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.downButton.setIcon(icon2)
        self.downButton.setIconSize(QtCore.QSize(24, 24))
        self.downButton.setObjectName("downButton")
        self.horizontalLayout.addWidget(self.downButton)
        self.deleteButton = QtWidgets.QToolButton(self.widget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../images/baseline-delete-24px.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteButton.setIcon(icon3)
        self.deleteButton.setIconSize(QtCore.QSize(24, 24))
        self.deleteButton.setObjectName("deleteButton")
        self.horizontalLayout.addWidget(self.deleteButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.widget)
        self.line = QtWidgets.QFrame(Toolbox)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label_2 = QtWidgets.QLabel(Toolbox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.widget_2 = QtWidgets.QWidget(Toolbox)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout.setObjectName("gridLayout")
        self.toolButton_8 = QtWidgets.QToolButton(self.widget_2)
        self.toolButton_8.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_8.setObjectName("toolButton_8")
        self.gridLayout.addWidget(self.toolButton_8, 1, 3, 1, 1)
        self.toolButton_11 = QtWidgets.QToolButton(self.widget_2)
        self.toolButton_11.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_11.setObjectName("toolButton_11")
        self.gridLayout.addWidget(self.toolButton_11, 2, 2, 1, 1)
        self.penButton = QtWidgets.QToolButton(self.widget_2)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../images/baseline-edit-24px.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.penButton.setIcon(icon4)
        self.penButton.setIconSize(QtCore.QSize(24, 24))
        self.penButton.setObjectName("penButton")
        self.gridLayout.addWidget(self.penButton, 1, 0, 1, 1)
        self.toolButton_10 = QtWidgets.QToolButton(self.widget_2)
        self.toolButton_10.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_10.setObjectName("toolButton_10")
        self.gridLayout.addWidget(self.toolButton_10, 2, 1, 1, 1)
        self.toolButton_9 = QtWidgets.QToolButton(self.widget_2)
        self.toolButton_9.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_9.setObjectName("toolButton_9")
        self.gridLayout.addWidget(self.toolButton_9, 2, 0, 1, 1)
        self.toolButton_7 = QtWidgets.QToolButton(self.widget_2)
        self.toolButton_7.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_7.setObjectName("toolButton_7")
        self.gridLayout.addWidget(self.toolButton_7, 1, 1, 1, 1)
        self.toolButton_6 = QtWidgets.QToolButton(self.widget_2)
        self.toolButton_6.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_6.setObjectName("toolButton_6")
        self.gridLayout.addWidget(self.toolButton_6, 1, 2, 1, 1)
        self.toolButton_12 = QtWidgets.QToolButton(self.widget_2)
        self.toolButton_12.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_12.setObjectName("toolButton_12")
        self.gridLayout.addWidget(self.toolButton_12, 2, 3, 1, 1)
        self.verticalLayout.addWidget(self.widget_2)

        self.retranslateUi(Toolbox)
        QtCore.QMetaObject.connectSlotsByName(Toolbox)

    def retranslateUi(self, Toolbox):
        _translate = QtCore.QCoreApplication.translate
        Toolbox.setWindowTitle(_translate("Toolbox", "Form"))
        self.label_3.setText(_translate("Toolbox", "Layers"))
        self.label.setText(_translate("Toolbox", "Opacity"))
        self.addButton.setText(_translate("Toolbox", "..."))
        self.upButton.setText(_translate("Toolbox", "..."))
        self.downButton.setText(_translate("Toolbox", "..."))
        self.deleteButton.setText(_translate("Toolbox", "..."))
        self.label_2.setText(_translate("Toolbox", "Tools"))
        self.toolButton_8.setText(_translate("Toolbox", "..."))
        self.toolButton_11.setText(_translate("Toolbox", "..."))
        self.penButton.setText(_translate("Toolbox", "..."))
        self.toolButton_10.setText(_translate("Toolbox", "..."))
        self.toolButton_9.setText(_translate("Toolbox", "..."))
        self.toolButton_7.setText(_translate("Toolbox", "..."))
        self.toolButton_6.setText(_translate("Toolbox", "..."))
        self.toolButton_12.setText(_translate("Toolbox", "..."))


